正式リリース前ソースレビュー
Fintan-contents/promptis pull request #1
Opened 2024-10-21 02:51 UTC by kiririmode-tis

2024-10-23 05:59 UTC, tisurgm requested changes
プロダクションコードを中心にレビューしました（あまり待たせるわけにもいかないと判断し、テストコードはまだ見ていません）。
また、`src/openapi`以下の自動生成されたコードは対象外としました。

2024-10-23 05:59 UTC, tisurgm commented on src/chatutil.ts
> +interface IFileChatResponseStream extends vscode.ChatResponseStream {
`interface`の接頭辞に`I`を付ける慣習は無いと思います。
参考までにいくつかのスタイルガイドのURLを挙げます。

- https://typescript-jp.gitbook.io/deep-dive/styleguide#intfsu
- https://google.github.io/styleguide/tsguide.html#naming-style
- https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names

※MicrosoftのガイドラインはTypeScriptコントリビューター向けなので少しベクトルは異なりますが、参考にはなるかな、と思い挙げています

2024-10-23 05:59 UTC, tisurgm commented on src/config.ts
> +  static getPath(key: string): string | undefined {
このメソッドは`private`で良さそうに思いました。

2024-10-29 00:29 UTC, tisurgm commented on src/util.ts
> +    // vscode.window.showInformationMessage(`ref: ${JSON.stringify(ref)}`);
5f2dead

2024-10-29 00:30 UTC, tisurgm commented on src/extension.ts
> +  for (const [key, value] of Object.entries(commandMap)) {
b8a511d

2024-10-29 00:30 UTC, tisurgm commented on src/api.ts
> +    vscode.workspace.getConfiguration("https").get<string>("proxy") ||
166b646

2024-10-29 00:30 UTC, tisurgm commented on src/chatHandler.ts
> +export interface IPromptisChatResult extends vscode.ChatResult {}
3cb0bef

2024-10-29 00:30 UTC, tisurgm commented on src/chatHandler.ts
> +export const chatHandler: vscode.ChatRequestHandler = async (
202e33e

2024-10-29 00:30 UTC, tisurgm commented on src/chatHandler.ts
> +  return {};
834a5d9

2024-10-29 00:31 UTC, tisurgm commented on src/config.ts
> +  static getPath(key: string): string | undefined {
8b8a27d

2024-10-29 00:31 UTC, tisurgm commented on src/chatutil.ts
> +interface IFileChatResponseStream extends vscode.ChatResponseStream {
d89684e

2024-10-29 00:33 UTC, tisurgm commented on src/chatHandler.ts
> +) {
8b8a27d

コミットを分け損ねていました、、、

2024-10-29 06:22 UTC, tisurgm commented on src/chatHandler.ts
> +  const timestamp = moment().format("YYYYMMDD-HHmmss");
直近3か月のダウンロード状況を見るとdayjsとdate-fnsのいずれかが候補になる。
https://npmtrends.com/date-fns-vs-dayjs-vs-js-joda-vs-luxon-vs-moment

![image](https://github.com/user-attachments/assets/d0477866-62b3-44fa-9614-7cbf59c91bff)

GitHubリポジトリのInsightsを見るとdate-fnsの方が活発に開発されているように見える。

- https://github.com/iamkun/dayjs/pulse
- https://github.com/date-fns/date-fns/pulse

dayjsは個人アカウントのリポジトリであるのに対して、date-fnsはdate-fnsのorganizationがある。

これらを踏まえてdate-fnsを採用する。

2024-10-29 07:06 UTC, tisurgm commented on src/chatHandler.ts
> +  const timestamp = moment().format("YYYYMMDD-HHmmss");
日付のフォーマットしか行っていないのでライブラリを導入するほどでもないと思い、自前で実装した。

17822a3

2024-10-29 07:12 UTC, tisurgm commented on src/api.ts
> +    httpAgent: agent,
実際にコメントを書いてみると、余計に混乱させるように感じたため、この指摘は取り下げます。
現状のままで特に問題はないと思いなおしました。

2024-10-29 07:12 UTC, tisurgm approved these changes

2024-11-03 06:37 UTC, kiririmode-tis commented on src/api.ts
> +    vscode.workspace.getConfiguration("https").get<string>("proxy") ||
おおお、なるほど、確かに `??` の利用の方が適切ですね。

2024-11-03 06:40 UTC, kiririmode-tis commented
レビュー＆修正対応ありがとうございました！
本件、すでに `main` 向けに対応いただいたので、`initial` PR としては merge し、 `initial` branch は削除する形で対応します。

2024-11-03 06:40 UTC, merged